//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ienumerable_Vs_IQueryable
{
    using System;
    using System.Collections.Generic;
    
    public partial class Library
    {
        public int BookID { get; set; }
        public string BookName { get; set; }
        public string BookColor { get; set; }
        public string BookWriter { get; set; }
    }
}
